# CONTROL FLOW
"""
CONTROL FLOWS REFERS TO THE ORDER IN WHICH INDIVIDUAL STATMENTS, INSTRUCTIONS OR FUNCTION CALLS ARE EXECUTED OR EVALUATED.
YOU CAN CONTROL FLOW USING:
"""

# CONDITIONAL STATEMENTS

"""
CONDITIONAL STATEMENTS IN PYTHON ALLOW YOU TO EXECUTE BLOCKS OF CODE BASED ON CERTAIN CONDITIONS.
"""

# if ...  elif ... else

if True:
    print("This will execute")
elif False:
    print("This will print")
else:
    print("This is the last part to exceute")

# LOOPS

"""
THEY ARE USED TO ITERATE OVER A SEQUENCE OF ELEMENTS OR EXECUTE A BLOCK OF CODE REPEATEDLY.
"""

# FOR LOOP
# USED TO ITERATE OVER SEQUENCES (LIKE LISTS, STRINGS, RANGES)
for i in range (1,11):
    print(i)
# WHILE LOOP
# RUNS AS LONG AS THE CONDITION IS TRUE
count = 0
while count < 5: # CONDITION
    print("Count is ", count)
    count += 1 # INCREMENT

 # FUNCTIONS

"""
THEY ALLOW YOU TO ENCAPSULATE REUSABLE PEICES OF CODE AND ENHANCE CODE MODULARITY.
"""
def add_sum(a,b):
    return a + b
result = add_sum(10, 20)
print(result)

